# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20171024_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='claim_indian_maternal',
            field=models.NullBooleanField(verbose_name='Claim to Indian descent via maternal grandparents'),
        ),
        migrations.AlterField(
            model_name='application',
            name='claim_indian_paternal',
            field=models.NullBooleanField(verbose_name='Claim to Indian descent via paternal grandparents'),
        ),
    ]
