# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_auto_20171024_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='claim_indian_maternal',
        ),
        migrations.RemoveField(
            model_name='application',
            name='claim_indian_paternal',
        ),
        migrations.AddField(
            model_name='application',
            name='claim_indian_descent',
            field=models.IntegerField(choices=[(1, 'Maternal grandparents'), (2, 'Paternal grandparents')], null=True, verbose_name='Claim to Indian descent'),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
