# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0005_auto_20171024_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hs_address',
        ),
        migrations.AddField(
            model_name='application',
            name='college_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='College name'),
        ),
        migrations.AddField(
            model_name='application',
            name='college_received_acceptance_letter',
            field=models.NullBooleanField(max_length=100, verbose_name='I have received an acceptance letter.'),
        ),
        migrations.AddField(
            model_name='application',
            name='home_address_1',
            field=models.CharField(blank=True, max_length=128, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='application',
            name='home_address_2',
            field=models.CharField(blank=True, max_length=128, verbose_name="address cont'd"),
        ),
        migrations.AddField(
            model_name='application',
            name='home_city',
            field=models.CharField(default='', max_length=64, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='application',
            name='home_state',
            field=models.CharField(default='GA', max_length=2, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='application',
            name='home_zip_code',
            field=models.CharField(default='', max_length=5, verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='application',
            name='hs_address_1',
            field=models.CharField(blank=True, max_length=128, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='application',
            name='hs_address_2',
            field=models.CharField(blank=True, max_length=128, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='application',
            name='hs_city',
            field=models.CharField(default='', max_length=64, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='application',
            name='hs_class_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hs_class_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hs_counselor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='hs_counselor_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='hs_counselor_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='hs_counselor_middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='hs_gpa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hs_state',
            field=models.CharField(default='GA', max_length=2, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='application',
            name='hs_zip_code',
            field=models.CharField(default='', max_length=5, verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='application',
            name='scores_act_composite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scores_act_math',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scores_act_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scores_act_science',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scores_act_writing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scores_ap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scores_sat_math',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scores_sat_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scores_sat_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scores_sat_writing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
