# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_auto_20171024_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='date_last_submitted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='essay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='list_dependents',
            field=models.TextField(blank=True, null=True, verbose_name='List of dependents currently entering college'),
        ),
        migrations.AddField(
            model_name='application',
            name='year',
            field=models.IntegerField(default='2018'),
        ),
        migrations.AlterField(
            model_name='application',
            name='claim_indian_descent',
            field=models.IntegerField(blank=True, choices=[(1, 'Maternal grandparents'), (2, 'Paternal grandparents')], null=True, verbose_name='Claim to Indian descent'),
        ),
        migrations.AlterField(
            model_name='application',
            name='home_city',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='application',
            name='home_state',
            field=models.CharField(blank=True, default='GA', max_length=2, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_city',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_class_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_class_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_state',
            field=models.CharField(blank=True, default='GA', max_length=2, verbose_name='State'),
        ),
    ]
