# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0008_auto_20171025_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='scores_ap',
        ),
    ]
