# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 20:43
from __future__ import unicode_literals

from django.db import migrations
import iasf.apply.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0011_application_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='activities',
            field=iasf.apply.fields.JSONListSchemaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='scores_ap',
            field=iasf.apply.fields.JSONListSchemaField(blank=True, null=True),
        ),
    ]
