# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0014_application_file_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file_act_scores',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='application',
            name='file_sat_scores',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
